" 关闭兼容模式（使用 Vim 设置而不是 Vi）
set nocompatible

syntax on

set number
set relativenumber
set hlsearch
set ignorecase
set smartcase

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set autoindent
set smartindent

" 保存 undo 历史（即使关闭文件）
if has('persistent_undo')
    set undofile
    set undodir=~/.vim/undo//
endif

set laststatus=2

" 总是显示光标位置
set ruler

" 更好的命令行补全
set wildmenu
set wildmode=longest:full,full

" 禁用响铃
set noerrorbells
set novisualbell

" 光标移动到行首/行尾时更平滑
set whichwrap+=<,>,h,l

" 文件编码
set encoding=utf-8
set fileencoding=utf-8


" plugin

call plug#begin()

Plug 'itchyny/lightline.vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
Plug 'jiangmiao/auto-pairs'

call plug#end()

map <F2> :NERDTreeToggle<CR>

let g:lightline = {'colorscheme': 'catppuccin_mocha'}
colorscheme catppuccin_mocha

set cursorline
highlight LineNr ctermfg=240 guifg=#6e6e6e
highlight CursorLineNr ctermfg=46 guifg=#50fa7b
highlight MatchParen ctermbg=68 guibg=#5fafff ctermfg=231 guifg=#ffffff
